### ISSUE TITLE
Django_CD_dev 최신 commit 적용 안됨 

### ISSUE THREAD

**Issue by ih-tjpark** [data-dev-course/project4-team1#25]
develop-** -> develop merge시 실행되는 git action 'django_CD_dev'에서 문제 발생

develop branch에 정상적으로 merge 됐으나 
서버 deploy과정에서 해당 명령어 진행 시
'git reset --hard origin/develop'

최신 commit이 아닌 이전 commit으로 git reset 진행됨

최신 commit으로 적용되도록 하는 작업 필요

**Comment by usiohc** [comment]
수정 완료
